### ISSUE TITLE
Program fails with «Not 8 bits per pixel PseudoColor.»

### ISSUE THREAD

**Issue by ffaf1** [dulsi/thrust#1]
Tried to `./configure && make` this, and

    f@extensa:/tmp/thrust$ ./xthrust
    Initializing soundIt library v0.04...no access to sound device: No such file or directory
    No sound.
    Not 8 bits per pixel PseudoColor.

the offending line is [this](https://github.com/dulsi/thrust/blob/master/src/X11.c#L582). I am not sure what and what not to do to fix this really.

**Comment by dulsi** [comment]
The solution is to build it with the SDL2 backend. Unfortunately I haven't been able to get the configure script to generate a Makefile to do that.

**Comment by ffaf1** [comment]
Uhhh and how to do it without the makefile then?

Il 13 agosto 2021 alle 08:04 dulsi ha scritto:

**Comment by dulsi** [comment]
Grab latest as I just created a CMakeLists.txt. Run:

./configure
mkdir build
cd build
cmake ..
make

The resulting executable is sdlthrust. The ./configure step is needed to generate the config.h file. I plan to fix that but it works for the moment. Let me know if you have any trouble,

**Comment by ffaf1** [comment]
Thanks @dulsi, that did it!

Il 13 agosto 2021 alle 12:58 dulsi ha scritto:
